# Lookbook configuration
project_name: "T3 Clone Components"
ui_theme: "indigo"
preview_paths: ["test/components/previews"]
preview_route: "/lookbook"
preview_layout: "component_preview"
preview_controller: "Lookbook::PreviewController"
preview_controller_include: []
preview_controller_exclude: []
preview_controller_helpers: []
preview_controller_helpers_include: []
preview_controller_helpers_exclude: []
preview_controller_helpers_autoload: true
preview_controller_helpers_autoload_paths: ["app/helpers"]
preview_controller_helpers_autoload_namespaces: ["ApplicationHelper"]
preview_controller_helpers_autoload_ignore: []
preview_controller_helpers_autoload_ignore_paths: []
preview_controller_helpers_autoload_ignore_namespaces: []
preview_controller_helpers_autoload_ignore_patterns: []
preview_controller_helpers_autoload_ignore_extensions: []
preview_controller_helpers_autoload_ignore_directories: []
preview_controller_helpers_autoload_ignore_files: []
preview_controller_helpers_autoload_ignore_modules: []
preview_controller_helpers_autoload_ignore_classes: []
preview_controller_helpers_autoload_ignore_methods: []
preview_controller_helpers_autoload_ignore_constants: []
preview_controller_helpers_autoload_ignore_variables: []
preview_controller_helpers_autoload_ignore_globals: []
preview_controller_helpers_autoload_ignore_locals: []
preview_controller_helpers_autoload_ignore_parameters: []
preview_controller_helpers_autoload_ignore_arguments: []
preview_controller_helpers_autoload_ignore_options: []
preview_controller_helpers_autoload_ignore_settings: []
preview_controller_helpers_autoload_ignore_configurations: []
preview_controller_helpers_autoload_ignore_preferences: []
preview_controller_helpers_autoload_ignore_defaults: []
preview_controller_helpers_autoload_ignore_values: []
preview_controller_helpers_autoload_ignore_data: []
preview_controller_helpers_autoload_ignore_content: []
preview_controller_helpers_autoload_ignore_text: []
preview_controller_helpers_autoload_ignore_html: []
preview_controller_helpers_autoload_ignore_markdown: []
preview_controller_helpers_autoload_ignore_yaml: []
preview_controller_helpers_autoload_ignore_json: []
preview_controller_helpers_autoload_ignore_xml: []
preview_controller_helpers_autoload_ignore_csv: []
preview_controller_helpers_autoload_ignore_tsv: []
preview_controller_helpers_autoload_ignore_ini: []
preview_controller_helpers_autoload_ignore_properties: []
preview_controller_helpers_autoload_ignore_env: []
preview_controller_helpers_autoload_ignore_secrets: []
preview_controller_helpers_autoload_ignore_credentials: [] 